apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  # labels:
  #   purpose: demonstrate-command
spec:
  containers:
  - name: server-container
    image: volfpe/s9y-k8s-server:1
    ports:
    - containerPort: 3000